name: Build and Publish jupyterlite page to GitHub Pages
on:
  schedule:
  - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Otter-Grader
      run: |
        pip install otter-grader
    - name: Run Otter Assign
      run: |
        otter assign --no-run-tests proj03.ipynb out
    - name: Build repo2jupyterlite
      uses: yuvipanda/repo2jupyterlite-action@main
    - name: Upload generated site
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./dist

  publish:
    needs: build
    if: github.ref == 'refs/heads/main' # specify 'refs/heads/master' if that is your main branch
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - name: Publish to GitHub Pages
      id: publish
      uses: actions/deploy-pages@v1
